name: 'Release Helper Action'
author: 'sudosubin'
description: 'A helper action for releasing actions without hassles.'

inputs:
  # <INPUTS_NAME>:
  #   description: ''
  #   required: true
  #   default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'white'
