name: 'build-test'

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Prepare action'
        run: |
          sudo npm install --global yarn
          yarn install --frozen-lockfile
      - name: 'Build action'
        run: |
          yarn run build
      - name: 'Test action'
        uses: ./
        with:
          prepare-command: 'yarn install --frozen-lockfile'
          build-command: 'yarn run build'
          target-branch: 'release-test'
          create-release: 'false'
