name: 'build-test'

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Prepare action'
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: 'Build action'
        run: |
          yarn run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: 'Test action'
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          prepare-command: 'yarn install --frozen-lockfile'
          build-command: 'yarn run build'
          target-branch: 'release-test'
