name: 'Build and Test'

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: 'Prepare action'
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: 'Build action'
        run: |
          yarn run build
          npm uninstall -g yarn
      - name: 'Test action'
        uses: ./
        with:
          prepare-command: 'yarn install --frozen-lockfile'
          build-command: 'yarn run build'
          target-branch: 'release-test'
          create-release: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
